name: genes-gpt
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - more-itertools
  - setuptools
  - click
  - jupyterlab
  - langchain
  - tiktoken
  - dash
  - python-dotenv
  - pytorch
  - pip:
      - pyfunctional
      - chromadb
      - pynction
      - unstructured
      - pdfminer.six
      - chromadb
      - unstructured-inference
      - unstructured[local-inference]
      - unstructured.PaddleOCR
      - pycomfort
      - scidownl
      - 'git+https://github.com/facebookresearch/detectron2.git@e2ce8dc#egg=detectron2'
